[package]
name = "choco-rs"
version = "0.1.0"
authors = ["AldairSoraki <aldair.gastelum@murena.io>"]
edition = "2024"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
